### ISSUE TITLE
`web.get_tasks` not working on 2.8.0

### ISSUE THREAD

**Issue by FilipeFcp** [flexcompute/tidy3d#2314]
**Describe the bug**
`web.get_tasks` not working on 2.8.0

**To Reproduce**
Just call `web.get_tasks(n)`

**Expected behavior**
Return the last n tasks

**Screenshots**
Not a screenshot, but this is the error:

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    web.get_tasks()
  File "/home/filipe/anaconda3/lib/python3.11/site-packages/tidy3d/web/api/connect_util.py", line 34, in web_fn_wrapped
    return web_fn(*args, **kwargs)
  File "/home/filipe/anaconda3/lib/python3.11/site-packages/tidy3d/web/api/webapi.py", line 921, in get_tasks
    tasks = folder.list_tasks()
  File "/home/filipe/anaconda3/lib/python3.11/site-packages/tidy3d/web/core/task_core.py", line 110, in list_tasks
    resp = http.get(f"tidy3d/projects/{self.folder_id}/tasks")
  File "/home/filipe/anaconda3/lib/python3.11/site-packages/tidy3d/web/core/http_util.py", line 143, in wrapper
    warning = result.get("warning")
AttributeError: 'list' object has no attribute 'get'
